name: Crowdin Upload Files

on:
  push:
    branches:
      - main
    paths:
      - addOns/help/src/main/javahelp/**
  workflow_dispatch:

jobs:
  upload:
    name: Upload Files
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Setup Java
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: 17
    - name: Upload Files
      env:
        CROWDIN_AUTH_TOKEN: ${{ secrets.ZAPBOT_CROWDIN_TOKEN }}
      run: ./gradlew crowdinUploadSourceFiles
